<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7Cm3MVm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Cm3MVm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7Cm3MVm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7Cm3MVm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7Cm3MVm\App_KernelDevDebugContainer([
    'container.build_hash' => '7Cm3MVm',
    'container.build_id' => '876dfbbe',
    'container.build_time' => 1594303477,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7Cm3MVm');
